codecov:
  notify: # ADVANCED USE ONLY
    # after: check ci status unless disabled via require_ci_to_pass
    after_n_builds: 1      # number of expected builds to recieve before sending notifications
    require_ci_to_pass: yes   # yes: will delay sending notifications until all ci is finished
    countdown: 30           # number of seconds to wait before first ci build check
    delay: 60               # number of seconds to wait between ci build checks
